// GENERATED by scripts/build-token-usage.mjs — do not edit by hand.
// Run `pnpm tokens:usage` after changing which tokens a component reads.

/**
 * Which `--octans-*` tokens each component names in its own source.
 *
 * Drives the Theme Builder's component filter, so you can ask "what does Badge
 * actually read?" instead of guessing from a token's name. Includes tokens a
 * component OVERRIDES as well as ones it reads — both are reasons a change to
 * that token shows up in that component.
 */
export const TOKEN_USAGE: Record<string, string[]> = {
  ActionList: [
    'border',
    'primary-surface',
    'radius-box',
    'surface',
    'surface-hover',
    'surface-selected',
    'text'
  ],
  AppFrame: [
    'border',
    'overlay',
    'radius-field',
    'scrollbar-thumb',
    'scrollbar-thumb-hover',
    'shadow-md',
    'shadow-sm',
    'surface',
    'surface-app',
    'surface-hover',
    'text'
  ],
  Badge: [
    'badge-error-surface',
    'badge-info-surface',
    'badge-ink',
    'badge-success-surface',
    'badge-surface-strength',
    'badge-warning-surface',
    'error',
    'info',
    'radius-full',
    'success',
    'surface',
    'surface-neutral',
    'text',
    'text-disabled',
    'text-error',
    'text-info',
    'text-success',
    'text-warning',
    'warning'
  ],
  Banner: [
    'banner-error-surface',
    'banner-info-surface',
    'banner-ink',
    'banner-success-surface',
    'banner-surface-strength',
    'banner-warning-surface',
    'error',
    'font',
    'info',
    'radius-box',
    'success',
    'surface',
    'surface-sunken',
    'text',
    'text-error',
    'text-info',
    'text-success',
    'text-warning',
    'warning'
  ],
  Button: [
    'border-input',
    'focus-ring',
    'primary',
    'primary-surface',
    'radius-field',
    'radius-full',
    'secondary-surface',
    'shadow-control',
    'shadow-sm',
    'surface',
    'surface-control',
    'surface-disabled',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-disabled',
    'text-link',
    'text-link-hover',
    'text-on-primary',
    'text-primary',
    'text-secondary',
    'text-subdued'
  ],
  Calendar: [
    'border',
    'primary',
    'radius-field',
    'radius-full',
    'surface',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-disabled',
    'text-subdued'
  ],
  CalendarHeatmap: [
    'border-strong',
    'focus-ring',
    'font',
    'surface',
    'surface-hover',
    'surface-sunken',
    'text'
  ],
  Card: [
    'border',
    'radius-box',
    'surface',
    'surface-sunken',
    'text'
  ],
  Checkbox: [
    'border-input',
    'error-surface',
    'radius-field',
    'surface',
    'surface-sunken',
    'text-disabled'
  ],
  Choice: [
    'text',
    'text-disabled',
    'text-subdued'
  ],
  ColorPicker: [
    'border-strong',
    'font',
    'font-mono',
    'primary',
    'radius-box',
    'radius-field',
    'radius-full',
    'surface',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-subdued'
  ],
  ColorSelector: [
    'border',
    'border-strong',
    'font',
    'font-mono',
    'primary',
    'radius-box',
    'radius-field',
    'radius-full',
    'shadow-md',
    'shadow-sm',
    'surface',
    'surface-disabled',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-disabled',
    'text-subdued'
  ],
  DataTable: [
    'border',
    'border-strong',
    'focus-ring',
    'primary',
    'radius-box',
    'radius-field',
    'scrim',
    'surface',
    'surface-app',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-subdued'
  ],
  DatePicker: [
    'border',
    'radius-field',
    'surface',
    'text',
    'text-subdued'
  ],
  Divider: [
    'border',
    'text-subdued'
  ],
  FileInput: [
    'border-input',
    'error',
    'error-surface',
    'primary',
    'radius-box',
    'radius-field',
    'surface',
    'surface-app',
    'surface-sunken',
    'text',
    'text-link',
    'text-primary'
  ],
  Filters: [
    'border',
    'scrim',
    'surface',
    'text-subdued'
  ],
  FooterHelp: [
    'text'
  ],
  GlobalNav: [
    'primary',
    'primary-active',
    'primary-surface',
    'radius-field',
    'state-mix',
    'surface',
    'surface-hover',
    'surface-nav',
    'surface-selected',
    'text',
    'text-on-nav',
    'text-subdued'
  ],
  GradientPicker: [
    'border-strong',
    'font',
    'primary',
    'radius-field',
    'surface',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-subdued'
  ],
  Heading: [
    'text'
  ],
  Icon: [
    'error',
    'info',
    'success',
    'surface',
    'warning'
  ],
  InlineError: [
    'text-error'
  ],
  KeyboardKey: [
    'border',
    'font-mono',
    'radius-field',
    'surface',
    'surface-raised',
    'text-subdued'
  ],
  Labelled: [
    'text',
    'text-error',
    'text-subdued'
  ],
  Layout: [
    'border',
    'text-subdued'
  ],
  List: [
    'surface',
    'surface-hover',
    'text',
    'text-error',
    'text-subdued'
  ],
  LoaderOverlay: [
    'neutral-0',
    'neutral-800',
    'radius-box',
    'shadow-md',
    'surface'
  ],
  LoadingBar: [
    'primary'
  ],
  Modal: [
    'border',
    'overlay',
    'radius-box',
    'scrim',
    'surface',
    'surface-raised',
    'surface-sunken',
    'text',
    'text-subdued'
  ],
  NavField: [
    'border-input',
    'radius-field',
    'surface',
    'surface-sunken',
    'text-subdued'
  ],
  Navigation: [
    'border',
    'primary',
    'primary-surface',
    'radius-field',
    'radius-full',
    'shadow-sm',
    'surface',
    'surface-app',
    'surface-hover',
    'surface-selected',
    'surface-sunken',
    'tertiary',
    'text',
    'text-subdued'
  ],
  OtpInput: [
    'font',
    'surface',
    'text'
  ],
  Page: [
    'scrim',
    'text',
    'text-subdued'
  ],
  PageActions: [
    'border'
  ],
  Pagination: [
    'border',
    'primary',
    'radius-field',
    'surface',
    'surface-hover',
    'text',
    'text-disabled',
    'text-on-primary',
    'text-subdued'
  ],
  ProgressBar: [
    'error-surface',
    'info-surface',
    'radius-full',
    'success-surface',
    'surface-sunken',
    'warning-surface'
  ],
  RadioButton: [
    'border-input',
    'error-surface',
    'surface',
    'surface-sunken',
    'text-disabled'
  ],
  RangeSlider: [
    'border-input',
    'radius-field',
    'surface',
    'surface-hover',
    'surface-sunken',
    'text'
  ],
  Rating: [
    'border-strong',
    'focus-ring',
    'radius-field',
    'rating',
    'surface',
    'text'
  ],
  ResourceList: [
    'border-strong',
    'radius-box'
  ],
  SaveBar: [
    'primary',
    'radius-field',
    'text-on-primary'
  ],
  ScrollPane: [
    'shadow-overflow'
  ],
  SegmentedControl: [
    'border',
    'radius-field',
    'shadow-sm',
    'surface',
    'surface-hover',
    'surface-raised',
    'surface-sunken',
    'text',
    'text-disabled',
    'text-subdued'
  ],
  Select: [
    'border',
    'border-input',
    'error',
    'error-surface',
    'focus-ring',
    'radius-field',
    'surface',
    'surface-hover',
    'surface-sunken',
    'text',
    'text-disabled',
    'text-subdued'
  ],
  Sheet: [
    'border',
    'scrim',
    'shadow-lg',
    'surface',
    'surface-sunken',
    'text',
    'text-subdued'
  ],
  SkeletonBodyText: [
    'radius-field'
  ],
  SkeletonDisplayText: [
    'radius-field'
  ],
  SkeletonPage: [
    'radius-field'
  ],
  Splitter: [
    'border-strong',
    'primary'
  ],
  StatGroup: [
    'text',
    'text-subdued'
  ],
  Tabs: [
    'border',
    'primary',
    'radius-field',
    'tabs-indicator-height',
    'tabs-indicator-offset',
    'tabs-indicator-radius',
    'tabs-label-gap',
    'text',
    'text-subdued'
  ],
  Tag: [
    'border-strong',
    'radius-field',
    'surface-neutral',
    'text',
    'text-disabled'
  ],
  TextField: [
    'radius-field',
    'surface',
    'text',
    'text-subdued'
  ],
  TextStyle: [
    'border',
    'font-mono',
    'radius-field',
    'surface-app',
    'text'
  ],
  Thumbnail: [
    'border',
    'font',
    'radius-field',
    'surface',
    'text-disabled'
  ],
  TimePicker: [
    'border',
    'radius-field',
    'surface',
    'text',
    'text-disabled',
    'text-subdued'
  ],
  ToastManager: [
    'border',
    'border-strong',
    'error',
    'info',
    'neutral-0',
    'neutral-800',
    'primary',
    'radius-box',
    'radius-field',
    'success',
    'surface',
    'surface-raised',
    'text',
    'warning'
  ],
  ToggleSwitch: [
    'border-input',
    'primary',
    'toggle-knob',
    'toggle-knob-icon'
  ],
  Tooltip: [
    'radius-box',
    'shadow-md',
    'surface-tooltip',
    'text-on-tooltip'
  ]
}

/** Component names that read at least one token, sorted. */
export const TOKEN_USAGE_COMPONENTS: string[] = Object.keys(TOKEN_USAGE)
